[build]
  command = "npm --prefix client run build"
  publish = "client/build"

[build.lifecycle]
  # Install dependencies INSIDE client before building
  preBuild = "npm --prefix client install"

[build.environment]
  NODE_VERSION = "18"
